-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 21:30:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_veiculo` (
  `id_tipo_veiculo` INT NOT NULL AUTO_INCREMENT,
  `nm_tipo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_tipo_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_fabricante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_fabricante` (
  `id_tipo_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nm_fabricante` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tipo_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `ano_fabricacao` INT NOT NULL,
  `ano_modelo` INT NOT NULL,
  `chassi` VARCHAR(17) NOT NULL,
  `placa` VARCHAR(8) NULL,
  `renavam` VARCHAR(11) NULL,
  `km` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `potencia` FLOAT NOT NULL,
  `portas` TINYINT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `tipo_veiculo_id_tipo_veiculo` INT NOT NULL,
  `tipo_fabricante_id_tipo_fabricante` INT NOT NULL,
  PRIMARY KEY (`id_veiculo`),
  INDEX `fk_veiculo_tipo_veiculo1_idx` (`tipo_veiculo_id_tipo_veiculo` ASC),
  INDEX `fk_veiculo_tipo_fabricante1_idx` (`tipo_fabricante_id_tipo_fabricante` ASC),
  CONSTRAINT `fk_veiculo_tipo_veiculo1`
    FOREIGN KEY (`tipo_veiculo_id_tipo_veiculo`)
    REFERENCES `mydb`.`tipo_veiculo` (`id_tipo_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_tipo_fabricante1`
    FOREIGN KEY (`tipo_fabricante_id_tipo_fabricante`)
    REFERENCES `mydb`.`tipo_fabricante` (`id_tipo_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_cliente` (
  `id_tipo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nm_tipo_cliente` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_tipo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `tipo_cliente_id_tipo_cliente` INT NOT NULL,
  `nm_cliente` VARCHAR(45) NOT NULL,
  `CPFCNPJ` INT NOT NULL,
  `CNH` VARCHAR(15) NOT NULL,
  `cnh_venc` VARCHAR(10) NOT NULL,
  `dt_nasc` VARCHAR(10) NULL,
  `RG` VARCHAR(15) NULL,
  `IM` VARCHAR(45) NULL,
  `nm_responsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_tipo_cliente1_idx` (`tipo_cliente_id_tipo_cliente` ASC),
  CONSTRAINT `fk_cliente_tipo_cliente1`
    FOREIGN KEY (`tipo_cliente_id_tipo_cliente`)
    REFERENCES `mydb`.`tipo_cliente` (`id_tipo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluguel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluguel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `dt_retorno` VARCHAR(10) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `pr_total` INT NOT NULL,
  `veiculo_id_veiculo` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`),
  INDEX `fk_aluguel_cliente1_idx` (`cliente_id_cliente` ASC),
  INDEX `fk_aluguel_veiculo1_idx` (`veiculo_id_veiculo` ASC),
  CONSTRAINT `fk_aluguel_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promocao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promocao` (
  `id_promocao` INT NOT NULL AUTO_INCREMENT,
  `nm_promocao` VARCHAR(45) NOT NULL,
  `porcentagem` TINYINT NOT NULL,
  PRIMARY KEY (`id_promocao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `dt_venda` VARCHAR(15) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `veiculo_id_veiculo` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC),
  INDEX `fk_venda_veiculo1_idx` (`veiculo_id_veiculo` ASC),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `funcao` TINYINT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`preco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`preco` (
  `pr_venda` INT NOT NULL,
  `veiculo_id_veiculo` INT NOT NULL,
  `pr_aluguel` INT NOT NULL,
  INDEX `fk_preco_venda_veiculo1_idx` (`veiculo_id_veiculo` ASC),
  PRIMARY KEY (`veiculo_id_veiculo`),
  CONSTRAINT `fk_preco_venda_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `cliente_id_cliente` INT NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(10) NULL,
  `telefone` VARCHAR(10) NULL,
  `nr_casa` INT NOT NULL,
  PRIMARY KEY (`cliente_id_cliente`),
  CONSTRAINT `fk_contato_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`opcionais_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`opcionais_veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`opcionais_veiculo` (
  `id_opcionais_veiculo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_opcionais_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo_has_opcionais_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veiculo_has_opcionais_veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veiculo_has_opcionais_veiculo` (
  `veiculo_id_veiculo` INT NOT NULL,
  `opcionais_veiculo_id_opcionais_veiculo` INT NOT NULL,
  PRIMARY KEY (`veiculo_id_veiculo`, `opcionais_veiculo_id_opcionais_veiculo`),
  INDEX `fk_veiculo_has_opcionais_veiculo_opcionais_veiculo1_idx` (`opcionais_veiculo_id_opcionais_veiculo` ASC),
  INDEX `fk_veiculo_has_opcionais_veiculo_veiculo1_idx` (`veiculo_id_veiculo` ASC),
  CONSTRAINT `fk_veiculo_has_opcionais_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `mydb`.`veiculo` (`id_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_opcionais_veiculo_opcionais_veiculo1`
    FOREIGN KEY (`opcionais_veiculo_id_opcionais_veiculo`)
    REFERENCES `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`tipo_veiculo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`tipo_veiculo` (`id_tipo_veiculo`, `nm_tipo`) VALUES (1, 'Carro');
INSERT INTO `mydb`.`tipo_veiculo` (`id_tipo_veiculo`, `nm_tipo`) VALUES (2, 'JetSki');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`tipo_fabricante`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (1, 'FIAT');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (2, 'Chevrolet');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (3, 'Ford');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (4, 'Volkswagen');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (5, 'Kawasaki');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (6, 'Yamaha');
INSERT INTO `mydb`.`tipo_fabricante` (`id_tipo_fabricante`, `nm_fabricante`) VALUES (7, 'Sea Doo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`tipo_cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`tipo_cliente` (`id_tipo_cliente`, `nm_tipo_cliente`) VALUES (1, 'Pessoa Física');
INSERT INTO `mydb`.`tipo_cliente` (`id_tipo_cliente`, `nm_tipo_cliente`) VALUES (2, 'Pessoa Jurídica');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`opcionais_veiculo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (1, 'Blindado');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (2, 'Ar Condicionado');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (3, 'Vidro Elétrico');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (4, 'Direção Hidráulica');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (5, 'Direção Elétrica');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (6, 'Multimídia');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (7, 'Teto Solar');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (8, '2 Lugares');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (9, '3 Lugares');
INSERT INTO `mydb`.`opcionais_veiculo` (`id_opcionais_veiculo`, `descricao`) VALUES (10, 'Colete Salva-vidas');

COMMIT;

